"use client";
import React, { JSX } from "react";
import { motion } from "framer-motion";
import { TrendingUp, Users, ShoppingBag, Award } from "lucide-react";

interface IncomeExample {
  icon: JSX.Element;
  title: string;
  description: string;
  example: string;
}

const incomeExamples: IncomeExample[] = [
  {
    icon: <ShoppingBag className="h-10 w-10 text-[#39b54b]" />,
    title: "Retail Profit",
    description:
      "Earn 20-30% profit on every product you sell directly to customers.",
    example:
      "Selling ₹50,000 worth of products monthly can earn you ₹10,000-15,000 in retail profit.",
  },
  {
    icon: <Users className="h-10 w-10 text-[#39b54b]" />,
    title: "Team Building",
    description:
      "Earn commissions from the sales generated by associates you sponsor and train.",
    example:
      "A team of 10 active associates can generate ₹20,000-40,000 in monthly team commissions.",
  },
  {
    icon: <TrendingUp className="h-10 w-10 text-[#39b54b]" />,
    title: "Leadership Bonuses",
    description:
      "Qualify for additional bonuses as you develop leaders within your organization.",
    example:
      "Developing 3-5 leaders can result in leadership bonuses of ₹30,000-60,000 monthly.",
  },
  {
    icon: <Award className="h-10 w-10 text-[#39b54b]" />,
    title: "Recognition & Rewards",
    description:
      "Earn trips, car incentives, and other rewards as you achieve business milestones.",
    example:
      "Top performers receive car allowances of ₹15,000-25,000 monthly and international trips.",
  },
];

const cardVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: (index: number) => ({
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.6,
      ease: "easeOut",
      delay: index * 0.2,
    },
  }),
};

export default function IncomeExamples() {
  return (
    <section>
      <h2 className="text-2xl font-bold mb-4">Income Potential</h2>
      <p className="text-gray-600 mb-8">
        Our business model offers multiple streams of income. Here are examples
        of how you can earn with us:
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {incomeExamples.map((example, index) => (
          <motion.div
            key={index}
            className="bg-white p-6 rounded-lg shadow-md"
            variants={cardVariants}
            initial="hidden"
            animate="visible"
            custom={index}
          >
            <div className="mb-4">{example.icon}</div>
            <h3 className="text-xl font-semibold mb-2">{example.title}</h3>
            <p className="text-gray-600 mb-2">{example.description}</p>
            <p className="text-sm bg-gray-50 p-3 rounded border-l-4 border-[#39b54b]">
              <strong>Example:</strong> {example.example}
            </p>
          </motion.div>
        ))}
      </div>

      <motion.div
        className="mt-8 p-4 bg-yellow-50 border-l-4 border-yellow-400 rounded"
        initial={{ width: 0 }}
        animate={{ width: "100%" }}
        transition={{ duration: 0.5, ease: "easeOut" }}
        style={{ transformOrigin: "left" }}
      >
        <p className="text-sm text-gray-700">
          <strong>Income Disclaimer:</strong> The income examples shown are for
          illustrative purposes only. Actual earnings will vary depending on
          individual effort, time commitment, skills, and other factors. Please
          see our full Income Disclaimer for more details.
        </p>
      </motion.div>
    </section>
  );
}
