'use client'
import { TrendingUp, Users, ShoppingBag, Award } from "lucide-react"
import { easeIn, motion } from "framer-motion"

// Mock income examples
const incomeExamples = [
  {
    icon: <ShoppingBag className="h-10 w-10 text-[#39b54b]" />,
    title: "Retail Profit",
    description: "Earn 20-30% profit on every product you sell directly to customers.",
    example: "Selling ₹50,000 worth of products monthly can earn you ₹10,000-15,000 in retail profit.",
  },
  {
    icon: <Users className="h-10 w-10 text-[#39b54b]" />,
    title: "Team Building",
    description: "Earn commissions from the sales generated by associates you sponsor and train.",
    example: "A team of 10 active associates can generate ₹20,000-40,000 in monthly team commissions.",
  },
  {
    icon: <TrendingUp className="h-10 w-10 text-[#39b54b]" />,
    title: "Leadership Bonuses",
    description: "Qualify for additional bonuses as you develop leaders within your organization.",
    example: "Developing 3-5 leaders can result in leadership bonuses of ₹30,000-60,000 monthly.",
  },
  {
    icon: <Award className="h-10 w-10 text-[#39b54b]" />,
    title: "Recognition & Rewards",
    description: "Earn trips, car incentives, and other rewards as you achieve business milestones.",
    example: "Top performers receive car allowances of ₹15,000-25,000 monthly and international trips.",
  },
]

export default function IncomeExamples() {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
        delayChildren: 0.1
      }
    }
  }

  const itemVariants = {
    hidden: { 
      opacity: 0, 
      y: 30, 
      scale: 0.95 
    },
    visible: {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: {
        duration: 0.5,
        ease: [0.20, 0.25, 0.30, 0.35] // Custom easing
      }
    }
  }

  return (
    <section>
    <motion.div
    initial={{x:-100, opacity:0}}
    animate={{x:0, opacity:1}}
    transition={{ease:easeIn}}
    >
      <h2 className="text-2xl font-bold mb-4">Income Potential</h2>
      <p className="text-gray-600 mb-8">
        Our business model offers multiple streams of income. Here are examples of how you can earn with us:
      </p>
    </motion.div>

      <motion.div 
        className="grid grid-cols-1 md:grid-cols-2 gap-8"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        {incomeExamples.map((example, index) => (
          <motion.div 
            key={index} 
            className="bg-white p-6 rounded-lg shadow-md"
            variants={itemVariants}
          >
            <div className="mb-4">{example.icon}</div>
            <h3 className="text-xl font-semibold mb-2">{example.title}</h3>
            <p className="text-gray-600 mb-2">{example.description}</p>
            <p className="text-sm bg-gray-50 p-3 rounded border-l-4 border-[#39b54b]">
              <strong>Example:</strong> {example.example}
            </p>
          </motion.div>
        ))}
      </motion.div>

      <div className="mt-8 p-4 bg-yellow-50 border-l-4 border-yellow-400 rounded">
        <p className="text-sm text-gray-700">
          <strong>Income Disclaimer:</strong> The income examples shown are for illustrative purposes only. Actual
          earnings will vary depending on individual effort, time commitment, skills, and other factors. Please see our
          full Income Disclaimer for more details.
        </p>
      </div>
    </section>
  )
}